name = "ftvkyo"
board = "hovert60"

includes = [
    "dt-bindings/zmk/bt.h",
]

defines = [
    ["DEFAULT", "0"],
    ["LOWER", "1"],
    ["RAISE", "2"],
    ["ADJUST", "3"],
]

extras = """
conditional_layers {
    compatible = "zmk,conditional-layers";
    tri_layer {
        if-layers = <LOWER RAISE>;
        then-layer = <ADJUST>;
    };
};
"""


[[layers]]

name = "Default"

[layers.keys]

l_0x0 = { d = "`", c = "&none" }
l_0x1 = { d = "1", c = "&none" }
l_0x2 = { d = "2", c = "&none" }
l_0x3 = { d = "3", c = "&none" }
l_0x4 = { d = "4", c = "&none" }
l_0x5 = { d = "5", c = "&none" }

l_1x0 = { d = "⇥", c = "&none" }
l_1x1 = { d = "Q", c = "&none" }
l_1x2 = { d = "W", c = "&none" }
l_1x3 = { d = "E", c = "&none" }
l_1x4 = { d = "R", c = "&none" }
l_1x5 = { d = "T", c = "&none" }

l_2x0 = { d = "⌃", c = "&none" }
l_2x1 = { d = "A", c = "&none" }
l_2x2 = { d = "S", c = "&none" }
l_2x3 = { d = "D", c = "&none" }
l_2x4 = { d = "F", c = "&none" }
l_2x5 = { d = "G", c = "&none" }

l_3x0 = { d = "⇧", c = "&none" }
l_3x1 = { d = "Z", c = "&none" }
l_3x2 = { d = "X", c = "&none" }
l_3x3 = { d = "C", c = "&none" }
l_3x4 = { d = "V", c = "&none" }
l_3x5 = { d = "B", c = "&none" }

l_4x0 = { d = " ", c = "&none" }
l_4x1 = { d = " ", c = "&none" }
l_4x2 = { d = "⌥", c = "&none" }
l_4x3 = { d = "⌘", c = "&none" }
l_4x4 = { d = "␣", c = "&none" }
l_4x5 = { d = " ", c = "&none" }

r_0x0 = { d = "6", c = "&none" }
r_0x1 = { d = "7", c = "&none" }
r_0x2 = { d = "8", c = "&none" }
r_0x3 = { d = "9", c = "&none" }
r_0x4 = { d = "0", c = "&none" }
r_0x5 = { d = "⌫", c = "&none" }

r_1x0 = { d = "Y", c = "&none" }
r_1x1 = { d = "U", c = "&none" }
r_1x2 = { d = "I", c = "&none" }
r_1x3 = { d = "O", c = "&none" }
r_1x4 = { d = "P", c = "&none" }
r_1x5 = { d = "'", c = "&none" }

r_2x0 = { d = "H", c = "&none" }
r_2x1 = { d = "J", c = "&none" }
r_2x2 = { d = "K", c = "&none" }
r_2x3 = { d = "L", c = "&none" }
r_2x4 = { d = ";", c = "&none" }
r_2x5 = { d = "⌃", c = "&none" }

r_3x0 = { d = "N", c = "&none" }
r_3x1 = { d = "M", c = "&none" }
r_3x2 = { d = ",", c = "&none" }
r_3x3 = { d = ".", c = "&none" }
r_3x4 = { d = "/", c = "&none" }
r_3x5 = { d = "⇧", c = "&none" }

r_4x0 = { d = " ", c = "&none" }
r_4x1 = { d = "␣", c = "&none" }
r_4x2 = { d = "⌅", c = "&none" }
r_4x3 = { d = "⎇", c = "&none" }
r_4x4 = { d = " ", c = "&none" }
r_4x5 = { d = " ", c = "&none" }


[[layers]]

name = "Lower"

[layers.keys]

l_0x0 = { d = "ポ", c = "&none" }
l_0x1 = { d = "テ", c = "&none" }
l_0x2 = { d = "ト", c = "&none" }
l_0x3 = { d = "ポ", c = "&none" }
l_0x4 = { d = "テ", c = "&none" }
l_0x5 = { d = "ト", c = "&none" }

l_1x0 = { d = "ポ", c = "&none" }
l_1x1 = { d = "テ", c = "&none" }
l_1x2 = { d = "ト", c = "&none" }
l_1x3 = { d = "ポ", c = "&none" }
l_1x4 = { d = "テ", c = "&none" }
l_1x5 = { d = "ト", c = "&none" }

l_2x0 = { d = "ポ", c = "&none" }
l_2x1 = { d = "テ", c = "&none" }
l_2x2 = { d = "ト", c = "&none" }
l_2x3 = { d = "ポ", c = "&none" }
l_2x4 = { d = "テ", c = "&none" }
l_2x5 = { d = "ト", c = "&none" }

l_3x0 = { d = "ポ", c = "&none" }
l_3x1 = { d = "テ", c = "&none" }
l_3x2 = { d = "ト", c = "&none" }
l_3x3 = { d = "ポ", c = "&none" }
l_3x4 = { d = "テ", c = "&none" }
l_3x5 = { d = "ト", c = "&none" }

l_4x0 = { d = "ポ", c = "&none" }
l_4x1 = { d = "テ", c = "&none" }
l_4x2 = { d = "ト", c = "&none" }
l_4x3 = { d = "ポ", c = "&none" }
l_4x4 = { d = "テ", c = "&none" }
l_4x5 = { d = "ト", c = "&none" }

r_0x0 = { d = "ポ", c = "&none" }
r_0x1 = { d = "テ", c = "&none" }
r_0x2 = { d = "ト", c = "&none" }
r_0x3 = { d = "ポ", c = "&none" }
r_0x4 = { d = "テ", c = "&none" }
r_0x5 = { d = "ト", c = "&none" }

r_1x0 = { d = "ポ", c = "&none" }
r_1x1 = { d = "テ", c = "&none" }
r_1x2 = { d = "ト", c = "&none" }
r_1x3 = { d = "ポ", c = "&none" }
r_1x4 = { d = "テ", c = "&none" }
r_1x5 = { d = "ト", c = "&none" }

r_2x0 = { d = "ポ", c = "&none" }
r_2x1 = { d = "テ", c = "&none" }
r_2x2 = { d = "ト", c = "&none" }
r_2x3 = { d = "ポ", c = "&none" }
r_2x4 = { d = "テ", c = "&none" }
r_2x5 = { d = "ト", c = "&none" }

r_3x0 = { d = "ポ", c = "&none" }
r_3x1 = { d = "テ", c = "&none" }
r_3x2 = { d = "ト", c = "&none" }
r_3x3 = { d = "ポ", c = "&none" }
r_3x4 = { d = "テ", c = "&none" }
r_3x5 = { d = "ト", c = "&none" }

r_4x0 = { d = "ポ", c = "&none" }
r_4x1 = { d = "テ", c = "&none" }
r_4x2 = { d = "ト", c = "&none" }
r_4x3 = { d = "ポ", c = "&none" }
r_4x4 = { d = "テ", c = "&none" }
r_4x5 = { d = "ト", c = "&none" }


[[layers]]

name = "Raise"

[layers.keys]

l_0x0 = { d = "ポ", c = "&none" }
l_0x1 = { d = "テ", c = "&none" }
l_0x2 = { d = "ト", c = "&none" }
l_0x3 = { d = "ポ", c = "&none" }
l_0x4 = { d = "テ", c = "&none" }
l_0x5 = { d = "ト", c = "&none" }

l_1x0 = { d = "ポ", c = "&none" }
l_1x1 = { d = "テ", c = "&none" }
l_1x2 = { d = "ト", c = "&none" }
l_1x3 = { d = "ポ", c = "&none" }
l_1x4 = { d = "テ", c = "&none" }
l_1x5 = { d = "ト", c = "&none" }

l_2x0 = { d = "ポ", c = "&none" }
l_2x1 = { d = "テ", c = "&none" }
l_2x2 = { d = "ト", c = "&none" }
l_2x3 = { d = "ポ", c = "&none" }
l_2x4 = { d = "テ", c = "&none" }
l_2x5 = { d = "ト", c = "&none" }

l_3x0 = { d = "ポ", c = "&none" }
l_3x1 = { d = "テ", c = "&none" }
l_3x2 = { d = "ト", c = "&none" }
l_3x3 = { d = "ポ", c = "&none" }
l_3x4 = { d = "テ", c = "&none" }
l_3x5 = { d = "ト", c = "&none" }

l_4x0 = { d = "ポ", c = "&none" }
l_4x1 = { d = "テ", c = "&none" }
l_4x2 = { d = "ト", c = "&none" }
l_4x3 = { d = "ポ", c = "&none" }
l_4x4 = { d = "テ", c = "&none" }
l_4x5 = { d = "ト", c = "&none" }

r_0x0 = { d = "ポ", c = "&none" }
r_0x1 = { d = "テ", c = "&none" }
r_0x2 = { d = "ト", c = "&none" }
r_0x3 = { d = "ポ", c = "&none" }
r_0x4 = { d = "テ", c = "&none" }
r_0x5 = { d = "ト", c = "&none" }

r_1x0 = { d = "ポ", c = "&none" }
r_1x1 = { d = "テ", c = "&none" }
r_1x2 = { d = "ト", c = "&none" }
r_1x3 = { d = "ポ", c = "&none" }
r_1x4 = { d = "テ", c = "&none" }
r_1x5 = { d = "ト", c = "&none" }

r_2x0 = { d = "ポ", c = "&none" }
r_2x1 = { d = "テ", c = "&none" }
r_2x2 = { d = "ト", c = "&none" }
r_2x3 = { d = "ポ", c = "&none" }
r_2x4 = { d = "テ", c = "&none" }
r_2x5 = { d = "ト", c = "&none" }

r_3x0 = { d = "ポ", c = "&none" }
r_3x1 = { d = "テ", c = "&none" }
r_3x2 = { d = "ト", c = "&none" }
r_3x3 = { d = "ポ", c = "&none" }
r_3x4 = { d = "テ", c = "&none" }
r_3x5 = { d = "ト", c = "&none" }

r_4x0 = { d = "ポ", c = "&none" }
r_4x1 = { d = "テ", c = "&none" }
r_4x2 = { d = "ト", c = "&none" }
r_4x3 = { d = "ポ", c = "&none" }
r_4x4 = { d = "テ", c = "&none" }
r_4x5 = { d = "ト", c = "&none" }


[[layers]]

name = "Adjust"

[layers.keys]

l_0x0 = { d = "ポ", c = "&none" }
l_0x1 = { d = "テ", c = "&none" }
l_0x2 = { d = "ト", c = "&none" }
l_0x3 = { d = "ポ", c = "&none" }
l_0x4 = { d = "テ", c = "&none" }
l_0x5 = { d = "ト", c = "&none" }

l_1x0 = { d = "ポ", c = "&none" }
l_1x1 = { d = "テ", c = "&none" }
l_1x2 = { d = "ト", c = "&none" }
l_1x3 = { d = "ポ", c = "&none" }
l_1x4 = { d = "テ", c = "&none" }
l_1x5 = { d = "ト", c = "&none" }

l_2x0 = { d = "ポ", c = "&none" }
l_2x1 = { d = "テ", c = "&none" }
l_2x2 = { d = "ト", c = "&none" }
l_2x3 = { d = "ポ", c = "&none" }
l_2x4 = { d = "テ", c = "&none" }
l_2x5 = { d = "ト", c = "&none" }

l_3x0 = { d = "ポ", c = "&none" }
l_3x1 = { d = "テ", c = "&none" }
l_3x2 = { d = "ト", c = "&none" }
l_3x3 = { d = "ポ", c = "&none" }
l_3x4 = { d = "テ", c = "&none" }
l_3x5 = { d = "ト", c = "&none" }

l_4x0 = { d = "ポ", c = "&none" }
l_4x1 = { d = "テ", c = "&none" }
l_4x2 = { d = "ト", c = "&none" }
l_4x3 = { d = "ポ", c = "&none" }
l_4x4 = { d = "テ", c = "&none" }
l_4x5 = { d = "ト", c = "&none" }

r_0x0 = { d = "ポ", c = "&none" }
r_0x1 = { d = "テ", c = "&none" }
r_0x2 = { d = "ト", c = "&none" }
r_0x3 = { d = "ポ", c = "&none" }
r_0x4 = { d = "テ", c = "&none" }
r_0x5 = { d = "ト", c = "&none" }

r_1x0 = { d = "ポ", c = "&none" }
r_1x1 = { d = "テ", c = "&none" }
r_1x2 = { d = "ト", c = "&none" }
r_1x3 = { d = "ポ", c = "&none" }
r_1x4 = { d = "テ", c = "&none" }
r_1x5 = { d = "ト", c = "&none" }

r_2x0 = { d = "ポ", c = "&none" }
r_2x1 = { d = "テ", c = "&none" }
r_2x2 = { d = "ト", c = "&none" }
r_2x3 = { d = "ポ", c = "&none" }
r_2x4 = { d = "テ", c = "&none" }
r_2x5 = { d = "ト", c = "&none" }

r_3x0 = { d = "ポ", c = "&none" }
r_3x1 = { d = "テ", c = "&none" }
r_3x2 = { d = "ト", c = "&none" }
r_3x3 = { d = "ポ", c = "&none" }
r_3x4 = { d = "テ", c = "&none" }
r_3x5 = { d = "ト", c = "&none" }

r_4x0 = { d = "ポ", c = "&none" }
r_4x1 = { d = "テ", c = "&none" }
r_4x2 = { d = "ト", c = "&none" }
r_4x3 = { d = "ポ", c = "&none" }
r_4x4 = { d = "テ", c = "&none" }
r_4x5 = { d = "ト", c = "&none" }
