name = "hovert60"

[slots]

# Left hand keys

l_0x0 = { pos = [0, 0.75] }
l_0x1 = { pos = [1, 0.75] }
l_0x2 = { pos = [2, 0.25] }
l_0x3 = { pos = [3, 0   ] }
l_0x4 = { pos = [4, 0.25] }
l_0x5 = { pos = [5, 0.5 ] }

l_1x0 = { pos = [0, 1.75] }
l_1x1 = { pos = [1, 1.75] }
l_1x2 = { pos = [2, 1.25] }
l_1x3 = { pos = [3, 1   ] }
l_1x4 = { pos = [4, 1.25] }
l_1x5 = { pos = [5, 1.5 ] }

l_2x0 = { pos = [0, 2.75] }
l_2x1 = { pos = [1, 2.75] }
l_2x2 = { pos = [2, 2.25] }
l_2x3 = { pos = [3, 2   ] }
l_2x4 = { pos = [4, 2.25] }
l_2x5 = { pos = [5, 2.5 ] }

l_3x0 = { pos = [0, 3.75] }
l_3x1 = { pos = [1, 3.75] }
l_3x2 = { pos = [2, 3.25] }
l_3x3 = { pos = [3, 3   ] }
l_3x4 = { pos = [4, 3.25] }
l_3x5 = { pos = [5, 3.5 ] }

l_4x0 = { pos = [2,    4.25] }
l_4x1 = { pos = [3,    4   ] }
l_4x2 = { pos = [4,    4.25] }
l_4x3 = { pos = [5.05, 4.65], angle = 15 }
l_4x4 = { pos = [6.15, 5.15], angle = 35 }
l_4x5 = { pos = [6.10, 3.90], angle = 25 }

# Right hand keys

r_0x0 = { pos = [10, 0.5 ] }
r_0x1 = { pos = [11, 0.25] }
r_0x2 = { pos = [12, 0   ] }
r_0x3 = { pos = [13, 0.25] }
r_0x4 = { pos = [14, 0.75] }
r_0x5 = { pos = [15, 0.75] }

r_1x0 = { pos = [10, 1.5 ] }
r_1x1 = { pos = [11, 1.25] }
r_1x2 = { pos = [12, 1   ] }
r_1x3 = { pos = [13, 1.25] }
r_1x4 = { pos = [14, 1.75] }
r_1x5 = { pos = [15, 1.75] }

r_2x0 = { pos = [10, 2.5 ] }
r_2x1 = { pos = [11, 2.25] }
r_2x2 = { pos = [12, 2   ] }
r_2x3 = { pos = [13, 2.25] }
r_2x4 = { pos = [14, 2.75] }
r_2x5 = { pos = [15, 2.75] }

r_3x0 = { pos = [10, 3.5 ] }
r_3x1 = { pos = [11, 3.25] }
r_3x2 = { pos = [12, 3   ] }
r_3x3 = { pos = [13, 3.25] }
r_3x4 = { pos = [14, 3.75] }
r_3x5 = { pos = [15, 3.75] }

r_4x0 = { pos = [8.9, 3.90], angle = -25 }
r_4x1 = { pos = [8.85, 5.15], angle = -35 }
r_4x2 = { pos = [9.95, 4.65], angle = -15 }
r_4x3 = { pos = [11,    4.25] }
r_4x4 = { pos = [12,    4   ] }
r_4x5 = { pos = [13,    4.25] }
